PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ifc:  <http://ifcowl.openbimstandards.org/IFC4x3#>
PREFIX ifcPlus: <http://ifcowl.openbimstandards.org/IFC4x3plus#>

INSERT {
    GRAPH <http://example.org/inferred> {
        ?start ifcPlus:feedsIndirectly ?end .
    }
}
WHERE {
  ?start rdf:type ifcPlus:FlowCarrier ;
         ifcPlus:hasPort ?startPort .

  ?startPort rdf:type ifc:IfcDistributionPort ;
             ifcPlus:feedsPort ?endPort .

  ?endPort rdf:type ifc:IfcDistributionPort .

  ?end rdf:type ifcPlus:FlowCarrier ;
       ifcPlus:hasPort ?endPort .
}