PREFIX ifc: <http://ifcowl.openbimstandards.org/IFC4x3#>
PREFIX ifcPlus: <http://ifcowl.openbimstandards.org/IFC4x3plus#>

INSERT { ?start ifcPlus:Feeds ?end }
WHERE {
    ?start a ifc:IfcDistributionElement ;
    	ifcPlus:HasPort ?start_port .
    ?end a ifc:IfcDistributionElement ;
    	ifcPlus:HasPort ?end_port .

    ?start_port a ifc:IfcDistributionPort .
    ?end_port a ifc:IfcDistributionPort .

    ?start_port ifcPlus:FeedsPort ?end_port .
}
