PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ifc:  <http://ifcowl.openbimstandards.org/IFC4x3#>
PREFIX ifcPlus: <http://ifcowl.openbimstandards.org/IFC4x3plus#>

INSERT {
    GRAPH <http://example.org/inferred> {
        ?relatedElement ifcPlus:hasLocation ?space .
    }
}
WHERE {
  ?space rdf:type ifc:IfcSpatialStructureElement ;
         ifc:ContainsElements ?spatialStructure .

  ?spatialStructure rdf:type ifc:IfcRelContainedInSpatialStructure ;
                    ifc:RelatedElements ?relatedElement .

  ?relatedElement rdf:type ifc:IfcDistributionElement .
}