PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX ifc:  <http://ifcowl.openbimstandards.org/IFC4x3#>
PREFIX ifcPlus: <http://ifcowl.openbimstandards.org/IFC4x3plus#>

INSERT {
    GRAPH <http://example.org/inferred> {
        ?space ifcPlus:isExternal "true"^^xsd:boolean .
    }
}
WHERE {
  ?space rdf:type ifc:IfcSpace ;
         ifcPlus:HasWall ?wall .

  ?wall rdf:type ifc:IfcWall ;
        ifcPlus:HasPropertySet ?pset .

  ?pset rdf:type ifc:IfcPropertySet ;
        ifc:Name "Pset_WallCommon" ;
        ifc:HasProperties ?prop .

  ?prop ifc:Name "IsExternal" ;
        ifc:NominalValue "true"^^xsd:boolean .
}