PREFIX ifc: <http://ifcowl.openbimstandards.org/IFC4x3#>
PREFIX ifcPlus: <http://ifcowl.openbimstandards.org/IFC4x3plus#>

INSERT { ?start ifcPlus:IsConnectedToByDuct ?end }
WHERE {
    ?start a ifcPlus:Device ;
        ifcPlus:Feeds ?start_pipe .

    ?start_pipe a ifcPlus:Duct ;
        ifcPlus:FeedsIndirectly* ?end_pipe .

    ?end_pipe a ifcPlus:Duct ;
        ifcPlus:Feeds ?end .

    ?end a ifcPlus:Device .
}
